version: '3.8'
services:
  nestjs-template:
    container_name: nestjs-template
    build:
      context: .
      dockerfile: ./apps/nestjs-template/Dockerfile
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - db
    env_file:
      - .env.local.compose
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'
      - '14268:14268'
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    volumes:
      - jaeger-data:/var/lib/jaeger
volumes:
  db:
    driver: local
  pgadmin-data:
    driver: local
  jaeger-data:
    driver: local
